import { Bell, ChefHat, LogOut } from "lucide-react";
import { logout } from "@/app/actions/auth";
import { Button } from "@/components/ui/button";
import type { SessionProfile } from "@/types";
import { WorkspaceSelector } from "@/components/shared/workspace-selector";

export function AppHeader({ profile, title }: { profile: SessionProfile; title: string }) {
  const initials = profile.full_name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <header className="sticky top-0 z-30 flex h-[72px] min-w-0 items-center justify-between border-b bg-white/90 px-4 shadow-[0_1px_0_rgba(15,23,42,0.02)] backdrop-blur-xl sm:px-6 lg:px-8 xl:px-10"><div className="min-w-0"><p className="truncate font-display text-base font-bold tracking-tight sm:text-lg">{title}</p><p className="hidden text-xs text-muted-foreground sm:block">Manage today&apos;s restaurant operations</p></div><div className="flex min-w-0 items-center gap-1.5 sm:gap-2"><WorkspaceSelector profile={profile}/><span className="mx-1 hidden h-7 w-px bg-border sm:block"/><Button variant="ghost" size="icon" aria-label="Notifications" className="relative rounded-full"><Bell className="h-5 w-5"/><span className="absolute right-2.5 top-2.5 h-2 w-2 rounded-full border-2 border-white bg-blue-600" aria-hidden="true"/></Button><div className="hidden items-center gap-2.5 md:flex"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white" aria-hidden="true">{initials}</span><div className="text-left"><p className="max-w-40 truncate text-sm font-semibold leading-5">{profile.full_name}</p><p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">{profile.membership.role}</p></div></div><form action={logout}><Button variant="ghost" size="icon" aria-label="Sign out" className="rounded-full text-muted-foreground hover:text-foreground"><LogOut className="h-5 w-5"/></Button></form></div></header>
}
export function Brand() { return <div className="flex h-[72px] shrink-0 items-center gap-3 border-b border-white/[0.08] px-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-blue-700 text-white shadow-lg shadow-blue-950/30"><ChefHat className="h-5 w-5"/></span><span><span className="block font-display text-lg font-bold tracking-tight text-white">RestroSync</span><span className="block text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">Admin console</span></span></div>; }
