"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/auth/session";
import { categorySchema, menuItemSchema, settingsSchema, tableSchema } from "@/lib/validations";
export type ActionState={ok?:boolean;error?:string};
export async function saveCategory(_:ActionState,formData:FormData):Promise<ActionState>{const profile=await requireRole("OWNER","ADMIN");const raw={...Object.fromEntries(formData),active:formData.get("active")==="on"};const parsed=categorySchema.safeParse(raw);if(!parsed.success)return{error:parsed.error.issues[0]?.message};const{id,sortOrder,...rest}=parsed.data;const supabase=await createClient();const payload={restaurant_id:profile.membership.restaurant_id,name:rest.name,sort_order:sortOrder,active:rest.active};const result=id?await supabase.from("categories").update(payload).eq("id",id).eq("restaurant_id",profile.membership.restaurant_id):await supabase.from("categories").insert(payload);if(result.error)return{error:result.error.message};revalidatePath("/admin/menu");return{ok:true}}
export async function deleteCategory(id:string):Promise<ActionState>{const profile=await requireRole("OWNER","ADMIN");const supabase=await createClient();const{error}=await supabase.from("categories").delete().eq("id",id).eq("restaurant_id",profile.membership.restaurant_id);if(error)return{error:error.message};revalidatePath("/admin/menu");return{ok:true}}
export async function saveMenuItem(_:ActionState,formData:FormData):Promise<ActionState>{const profile=await requireRole("OWNER","ADMIN");const raw={...Object.fromEntries(formData),available:formData.get("available")==="on",active:formData.get("active")==="on"};const parsed=menuItemSchema.safeParse(raw);if(!parsed.success)return{error:parsed.error.issues[0]?.message};const{id,categoryId,pricePaise,foodType,...rest}=parsed.data;const supabase=await createClient();const payload={...rest,restaurant_id:profile.membership.restaurant_id,category_id:categoryId,price_paise:pricePaise,food_type:foodType,description:rest.description||null};const result=id?await supabase.from("menu_items").update(payload).eq("id",id).eq("restaurant_id",profile.membership.restaurant_id):await supabase.from("menu_items").insert(payload);if(result.error)return{error:result.error.message};revalidatePath("/admin/menu");revalidatePath("/cashier");return{ok:true}}
export async function saveTable(_:ActionState,formData:FormData):Promise<ActionState>{const profile=await requireRole("OWNER","ADMIN");const raw={...Object.fromEntries(formData),active:formData.get("active")==="on"};const parsed=tableSchema.safeParse(raw);if(!parsed.success)return{error:parsed.error.issues[0]?.message};const{id,...values}=parsed.data;const supabase=await createClient();const payload={restaurant_id:profile.membership.restaurant_id,name:values.name,capacity:values.capacity,active:values.active};const result=id?await supabase.from("restaurant_tables").update(payload).eq("id",id).eq("restaurant_id",profile.membership.restaurant_id):await supabase.from("restaurant_tables").insert(payload);if(result.error)return{error:result.error.message};revalidatePath("/admin/tables");return{ok:true}}
export async function saveSettings(_:ActionState,formData:FormData):Promise<ActionState>{const profile=await requireRole("OWNER","ADMIN");const parsed=settingsSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0]?.message};const v=parsed.data;const supabase=await createClient();const{error}=await supabase.from("restaurant_settings").upsert({restaurant_id:profile.membership.restaurant_id,restaurant_name:v.restaurantName,address:v.address,phone:v.phone,gstin:v.gstin,tax_basis_points:v.taxBasisPoints,currency:v.currency.toUpperCase(),receipt_footer:v.receiptFooter,service_charge_basis_points:v.serviceChargeBasisPoints,upi_id:v.upiId||null,upi_payee_name:v.upiPayeeName||null},{onConflict:"restaurant_id"});if(error)return{error:error.message};revalidatePath("/admin/settings");return{ok:true}}
