"use server";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { cancellationSchema, createOrderSchema, paymentSchema } from "@/lib/validations";
import type { KotStatus } from "@/types";
import { z } from "zod";

export type RpcState = { ok?: boolean; error?: string; data?: unknown };
export async function createAndSendOrder(payload: unknown): Promise<RpcState> { const profile=await requireRole("CASHIER", "ADMIN", "OWNER"); const parsed = createOrderSchema.safeParse(payload); if (!parsed.success) return { error: parsed.error.issues[0]?.message }; const supabase = await createClient(); const { data, error } = await supabase.rpc("create_order_with_kot", { p_payload: { ...parsed.data, restaurantId:profile.membership.restaurant_id } }); if (error) return { error: error.message }; revalidatePath("/cashier"); return { ok: true, data }; }
export async function addItemsToOrder(orderId: string, items: unknown): Promise<RpcState> { await requireRole("CASHIER", "ADMIN", "OWNER"); const parsed = createOrderSchema.shape.items.safeParse(items); if (!parsed.success) return { error: parsed.error.issues[0]?.message }; const supabase = await createClient(); const { data, error } = await supabase.rpc("append_order_items_and_create_kot", { p_order_id: orderId, p_items: parsed.data }); if (error) return { error: error.message }; revalidatePath("/cashier"); return { ok: true, data }; }
export async function cancelOrder(payload: unknown): Promise<RpcState> { await requireRole("CASHIER", "ADMIN", "OWNER"); const parsed = cancellationSchema.safeParse(payload); if (!parsed.success) return { error: parsed.error.issues[0]?.message }; const supabase = await createClient(); const { error } = await supabase.rpc("cancel_order", { p_order_id: parsed.data.orderId, p_reason: parsed.data.reason }); if (error) return { error: error.message }; revalidatePath("/cashier"); revalidatePath("/admin/orders"); return { ok: true }; }
export async function completePayment(payload: unknown): Promise<RpcState> { await requireRole("CASHIER", "ADMIN", "OWNER"); const parsed = paymentSchema.safeParse(payload); if (!parsed.success) return { error: parsed.error.issues[0]?.message }; const supabase = await createClient(); const { error } = await supabase.rpc("complete_order_payment", { p_order_id: parsed.data.orderId, p_method: parsed.data.method, p_idempotency_key: parsed.data.idempotencyKey }); if (error) return { error: error.message }; revalidatePath("/cashier"); return { ok: true }; }
export async function generateBill(orderId: string): Promise<RpcState> { await requireRole("CASHIER", "ADMIN", "OWNER"); const parsed = (await import("zod")).z.uuid().safeParse(orderId); if (!parsed.success) return { error: "Invalid order" }; const supabase = await createClient(); const { error } = await supabase.rpc("generate_order_bill", { p_order_id: parsed.data }); if (error) return { error: error.message }; revalidatePath("/cashier"); return { ok: true }; }
export async function updateKotStatus(kotId: string, status: KotStatus): Promise<RpcState> { await requireRole("KITCHEN", "ADMIN", "OWNER"); if (!(["PREPARING", "READY"] as KotStatus[]).includes(status)) return { error: "Invalid KOT status" }; const supabase = await createClient(); const { error } = await supabase.rpc("update_kot_status", { p_kot_id: kotId, p_status: status }); if (error) return { error: error.message }; revalidatePath("/kitchen"); revalidatePath("/cashier"); return { ok: true }; }

export async function acceptGuestOrder(orderId: string): Promise<RpcState> { await requireRole("OWNER","ADMIN","CASHIER","KITCHEN"); if(!z.uuid().safeParse(orderId).success)return{error:"Invalid order"}; const supabase=await createClient(); const{error}=await supabase.rpc("accept_guest_order",{p_order_id:orderId}); if(error)return{error:error.message}; revalidatePath("/kitchen");revalidatePath("/cashier");return{ok:true}; }
export async function setOrderEstimate(orderId:string,minutes:number):Promise<RpcState>{await requireRole("OWNER","ADMIN","CASHIER","KITCHEN");const parsed=z.object({orderId:z.uuid(),minutes:z.number().int().min(1).max(240)}).safeParse({orderId,minutes});if(!parsed.success)return{error:"Estimate must be between 1 and 240 minutes"};const supabase=await createClient();const{error}=await supabase.rpc("set_order_estimate",{p_order_id:orderId,p_minutes:minutes});if(error)return{error:error.message};revalidatePath("/kitchen");revalidatePath("/cashier");return{ok:true};}
export async function closeTableVisit(tableId:string):Promise<RpcState>{await requireRole("OWNER","ADMIN","CASHIER");if(!z.uuid().safeParse(tableId).success)return{error:"Invalid table"};const supabase=await createClient();const{error}=await supabase.rpc("close_table_visit",{p_table_id:tableId});if(error)return{error:error.message};revalidatePath("/cashier");revalidatePath("/admin/tables");return{ok:true};}
export async function verifyGuestPayment(claimId:string,approved:boolean,reason?:string):Promise<RpcState>{await requireRole("OWNER","ADMIN","CASHIER");if(!z.uuid().safeParse(claimId).success)return{error:"Invalid payment claim"};if(!approved&&(!reason||reason.trim().length<3))return{error:"Enter a rejection reason"};const supabase=await createClient();const{error}=await supabase.rpc("verify_guest_payment",{p_claim_id:claimId,p_approved:approved,p_reason:reason??null});if(error)return{error:error.message};revalidatePath("/cashier");return{ok:true};}
