import * as React from "react";
import { cn } from "@/lib/utils";

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("surface", className)} {...props} />; }
export function Badge({ className, tone = "neutral", ...props }: React.HTMLAttributes<HTMLSpanElement> & { tone?: "neutral" | "success" | "warning" | "danger" | "info" }) { const tones = { neutral: "bg-orange-50 text-orange-800", success: "bg-emerald-100 text-emerald-800", warning: "bg-amber-100 text-amber-800", danger: "bg-red-100 text-red-800", info: "bg-orange-100 text-orange-800" }; return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold", tones[tone], className)} {...props} />; }
export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cn("min-h-11 w-full rounded-xl border border-orange-100 bg-white px-3 text-sm placeholder:text-muted-foreground focus:border-orange-400 focus:ring-orange-500", className)} {...props} />); Input.displayName = "Input";
export const Textarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cn("min-h-24 w-full rounded-xl border border-orange-100 bg-white px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-orange-400 focus:ring-orange-500", className)} {...props} />); Textarea.displayName = "Textarea";
export function Label({ className, ...props }: React.LabelHTMLAttributes<HTMLLabelElement>) { return <label className={cn("mb-1.5 block text-sm font-semibold", className)} {...props} />; }
export function EmptyState({ icon: Icon, title, description }: { icon: React.ElementType; title: string; description: string }) { return <div className="flex min-h-52 flex-col items-center justify-center rounded-2xl border border-dashed border-orange-200 bg-white p-8 text-center"><span className="mb-3 grid h-12 w-12 place-items-center rounded-xl bg-orange-50 text-orange-600"><Icon className="h-6 w-6" aria-hidden="true"/></span><h3 className="font-display font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p></div>; }
