import { z } from "zod";

export const loginSchema = z.object({ email: z.email(), password: z.string().min(8).max(128) });
export const registrationSchema = z.object({ ownerName: z.string().trim().min(2).max(100), restaurantName: z.string().trim().min(2).max(120), address: z.string().trim().min(5).max(500), phone: z.string().trim().min(8).max(20), email: z.email(), password: z.string().min(10).max(128) });
export const invitationSchema = z.object({ email: z.email(), role: z.enum(["ADMIN","CASHIER","KITCHEN"]) });
export const categorySchema = z.object({ id: z.uuid().optional(), name: z.string().trim().min(2).max(60), sortOrder: z.coerce.number().int().min(0).max(999), active: z.coerce.boolean() });
export const menuItemSchema = z.object({ id: z.uuid().optional(), categoryId: z.uuid(), name: z.string().trim().min(2).max(100), description: z.string().trim().max(500).optional(), pricePaise: z.coerce.number().int().min(0).max(100_000_000), foodType: z.enum(["VEG", "NON_VEG"]), available: z.coerce.boolean(), active: z.coerce.boolean() });
export const tableSchema = z.object({ id: z.uuid().optional(), name: z.string().trim().min(1).max(30), capacity: z.coerce.number().int().min(1).max(50), active: z.coerce.boolean() });
export const settingsSchema = z.object({ restaurantName: z.string().trim().min(2).max(120), address: z.string().trim().max(500), phone: z.string().trim().min(8).max(20), gstin: z.string().trim().max(20), taxBasisPoints: z.coerce.number().int().min(0).max(10_000), currency: z.string().length(3), receiptFooter: z.string().trim().max(300), serviceChargeBasisPoints: z.coerce.number().int().min(0).max(10_000), upiId: z.string().trim().max(100).refine((value) => !value || /^[\w.-]+@[\w.-]+$/.test(value), "Enter a valid UPI ID"), upiPayeeName: z.string().trim().max(100) });
export const orderLineSchema = z.object({ menuItemId: z.uuid(), quantity: z.number().int().min(1).max(99), variantId: z.uuid().nullable(), addonIds: z.array(z.uuid()).max(20), notes: z.string().trim().max(300) });
export const createOrderSchema = z.object({ orderType: z.enum(["DINE_IN", "TAKEAWAY"]), tableId: z.uuid().nullable(), customerName: z.string().trim().max(100), customerPhone: z.string().trim().max(20), instructions: z.string().trim().max(500), discountType: z.enum(["NONE", "FIXED", "PERCENTAGE"]), discountValue: z.number().int().min(0), items: z.array(orderLineSchema).min(1) }).superRefine((value, ctx) => { if (value.orderType === "DINE_IN" && !value.tableId) ctx.addIssue({ code: "custom", path: ["tableId"], message: "Select a table for dine-in orders" }); });
export const cancellationSchema = z.object({ orderId: z.uuid(), reason: z.string().trim().min(3).max(300) });
export const paymentSchema = z.object({ orderId: z.uuid(), method: z.enum(["CASH", "UPI", "CARD"]), idempotencyKey: z.uuid() });
export const guestOrderSchema = z.object({ tableToken: z.string().min(32).max(200), submissionKey: z.uuid(), customerName: z.string().trim().min(1).max(80), instructions: z.string().trim().max(500), items: z.array(orderLineSchema.extend({ quantity: z.number().int().min(1).max(20) })).min(1).max(50) });
export const paymentClaimSchema = z.object({ tableToken: z.string().min(32).max(200), orderId: z.uuid(), transactionReference: z.string().trim().max(100).optional() });
