-- RestroSync initial schema. Run with `supabase db reset` locally or through the SQL editor.
create extension if not exists pgcrypto;

create type public.user_role as enum ('ADMIN','CASHIER','KITCHEN');
create type public.food_type as enum ('VEG','NON_VEG');
create type public.order_type as enum ('DINE_IN','TAKEAWAY');
create type public.order_status as enum ('DRAFT','CONFIRMED','PREPARING','READY','SERVED','COMPLETED','CANCELLED');
create type public.kot_status as enum ('NEW','PREPARING','READY');
create type public.table_status as enum ('AVAILABLE','OCCUPIED','BILLING');
create type public.payment_status as enum ('PENDING','PAID','REFUNDED');
create type public.payment_method as enum ('CASH','UPI','CARD');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null check (length(full_name) between 2 and 100), role public.user_role not null default 'CASHIER', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.restaurant_settings (id smallint primary key default 1 check (id=1), restaurant_name text not null default 'RestroSync Kitchen', address text not null default '', phone text not null default '', gstin text not null default '', tax_basis_points integer not null default 500 check (tax_basis_points between 0 and 10000), currency char(3) not null default 'INR', receipt_footer text not null default 'Thank you for dining with us!', service_charge_basis_points integer not null default 0 check (service_charge_basis_points between 0 and 10000), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.menu_items (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.categories(id) on delete restrict, name text not null, description text, price_paise bigint not null check (price_paise >= 0), food_type public.food_type not null, available boolean not null default true, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(category_id,name));
create table public.menu_variants (id uuid primary key default gen_random_uuid(), menu_item_id uuid not null references public.menu_items(id) on delete cascade, name text not null, price_delta_paise bigint not null default 0, active boolean not null default true, created_at timestamptz not null default now(), unique(menu_item_id,name));
create table public.addons (id uuid primary key default gen_random_uuid(), name text not null unique, price_paise bigint not null check(price_paise >= 0), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.menu_item_addons (menu_item_id uuid not null references public.menu_items(id) on delete cascade, addon_id uuid not null references public.addons(id) on delete cascade, primary key(menu_item_id,addon_id));
create table public.restaurant_tables (id uuid primary key default gen_random_uuid(), name text not null unique, capacity integer not null check(capacity between 1 and 50), status public.table_status not null default 'AVAILABLE', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create sequence public.order_number_seq start 1001;
create sequence public.kot_number_seq start 1001;
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique default ('ORD-'||to_char(current_date,'YYMMDD')||'-'||nextval('public.order_number_seq')), order_type public.order_type not null, status public.order_status not null default 'DRAFT', table_id uuid references public.restaurant_tables(id) on delete restrict, cashier_id uuid not null references public.profiles(id) on delete restrict, customer_name text, customer_phone text, instructions text, subtotal_paise bigint not null default 0 check(subtotal_paise>=0), discount_paise bigint not null default 0 check(discount_paise>=0), tax_paise bigint not null default 0 check(tax_paise>=0), service_charge_paise bigint not null default 0 check(service_charge_paise>=0), total_paise bigint not null default 0 check(total_paise>=0), payment_status public.payment_status not null default 'PENDING', payment_method public.payment_method, cancellation_reason text, cancelled_by uuid references public.profiles(id), cancelled_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint dine_in_requires_table check ((order_type='TAKEAWAY' and table_id is null) or (order_type='DINE_IN' and table_id is not null)), constraint cancellation_requires_reason check (status <> 'CANCELLED' or (cancellation_reason is not null and length(trim(cancellation_reason))>=3)));
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete restrict, menu_item_id uuid references public.menu_items(id) on delete set null, item_name text not null, unit_price_paise bigint not null check(unit_price_paise>=0), quantity integer not null check(quantity between 1 and 99), variant_id uuid references public.menu_variants(id) on delete set null, variant_name text, notes text, line_total_paise bigint not null check(line_total_paise>=0), sent_to_kitchen boolean not null default false, created_at timestamptz not null default now());
create table public.order_item_addons (id uuid primary key default gen_random_uuid(), order_item_id uuid not null references public.order_items(id) on delete restrict, addon_id uuid references public.addons(id) on delete set null, addon_name text not null, price_paise bigint not null check(price_paise>=0), created_at timestamptz not null default now());
create table public.kot_tickets (id uuid primary key default gen_random_uuid(), kot_number text not null unique default ('KOT-'||to_char(current_date,'YYMMDD')||'-'||nextval('public.kot_number_seq')), order_id uuid not null references public.orders(id) on delete restrict, status public.kot_status not null default 'NEW', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.kot_items (id uuid primary key default gen_random_uuid(), kot_id uuid not null references public.kot_tickets(id) on delete restrict, order_item_id uuid not null unique references public.order_items(id) on delete restrict, item_name text not null, quantity integer not null, variant_name text, addons_text text, notes text, created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete restrict, amount_paise bigint not null check(amount_paise>0), method public.payment_method not null, status public.payment_status not null default 'PAID', idempotency_key uuid not null unique, received_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, old_data jsonb, new_data jsonb, created_at timestamptz not null default now());

create index idx_menu_items_category on public.menu_items(category_id) where active;
create index idx_orders_created on public.orders(created_at desc);
create index idx_orders_status on public.orders(status,created_at desc);
create index idx_orders_table_active on public.orders(table_id) where status not in ('COMPLETED','CANCELLED');
create index idx_order_items_order on public.order_items(order_id);
create index idx_kot_status_created on public.kot_tickets(status,created_at);
create index idx_payments_created on public.payments(created_at desc);
create index idx_audit_entity on public.audit_logs(entity_type,entity_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger touch_profiles before update on public.profiles for each row execute function public.touch_updated_at();
create trigger touch_categories before update on public.categories for each row execute function public.touch_updated_at();
create trigger touch_menu_items before update on public.menu_items for each row execute function public.touch_updated_at();
create trigger touch_tables before update on public.restaurant_tables for each row execute function public.touch_updated_at();
create trigger touch_orders before update on public.orders for each row execute function public.touch_updated_at();
create trigger touch_kots before update on public.kot_tickets for each row execute function public.touch_updated_at();

create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and active $$;
create or replace function public.has_role(allowed public.user_role[]) returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_role()=any(allowed),false) $$;
revoke all on function public.current_role() from public; grant execute on function public.current_role() to authenticated;
revoke all on function public.has_role(public.user_role[]) from public; grant execute on function public.has_role(public.user_role[]) to authenticated;

alter table public.profiles enable row level security; alter table public.restaurant_settings enable row level security; alter table public.categories enable row level security; alter table public.menu_items enable row level security; alter table public.menu_variants enable row level security; alter table public.addons enable row level security; alter table public.menu_item_addons enable row level security; alter table public.restaurant_tables enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_item_addons enable row level security; alter table public.kot_tickets enable row level security; alter table public.kot_items enable row level security; alter table public.payments enable row level security; alter table public.audit_logs enable row level security;

create policy profiles_self_or_admin_read on public.profiles for select to authenticated using (id=auth.uid() or public.has_role(array['ADMIN']::public.user_role[]));
create policy profiles_admin_update on public.profiles for update to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy operational_settings_read on public.restaurant_settings for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[]));
create policy admin_settings_write on public.restaurant_settings for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy menu_read on public.categories for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy categories_admin on public.categories for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy items_read on public.menu_items for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy items_admin on public.menu_items for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy variants_read on public.menu_variants for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy variants_admin on public.menu_variants for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy addons_read on public.addons for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy addons_admin on public.addons for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy links_read on public.menu_item_addons for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy links_admin on public.menu_item_addons for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy tables_read on public.restaurant_tables for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy tables_admin on public.restaurant_tables for all to authenticated using (public.has_role(array['ADMIN']::public.user_role[])) with check (public.has_role(array['ADMIN']::public.user_role[]));
create policy orders_read on public.orders for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy order_items_read on public.order_items for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy order_addons_read on public.order_item_addons for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[]));
create policy kots_read on public.kot_tickets for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[])); create policy kot_items_read on public.kot_items for select to authenticated using (public.has_role(array['ADMIN','CASHIER','KITCHEN']::public.user_role[]));
create policy payments_admin_cashier_read on public.payments for select to authenticated using (public.has_role(array['ADMIN','CASHIER']::public.user_role[])); create policy audit_admin_read on public.audit_logs for select to authenticated using (public.has_role(array['ADMIN']::public.user_role[]));

create or replace function public.create_order_with_kot(p_payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare v_order uuid; v_kot uuid; v_line jsonb; v_item record; v_variant_id uuid; v_variant_name text; v_variant_delta bigint; v_order_item uuid; v_addons bigint; v_subtotal bigint:=0; v_discount bigint:=0; v_tax integer; v_service integer; v_line_total bigint; v_addon_names text;
begin
 if not public.has_role(array['ADMIN','CASHIER']::public.user_role[]) then raise exception 'Forbidden'; end if;
 if jsonb_array_length(p_payload->'items')=0 then raise exception 'At least one item is required'; end if;
 if p_payload->>'orderType'='DINE_IN' and nullif(p_payload->>'tableId','') is null then raise exception 'Table is required'; end if;
 if p_payload->>'orderType'='DINE_IN' then perform 1 from restaurant_tables where id=(p_payload->>'tableId')::uuid and active and status='AVAILABLE' for update; if not found then raise exception 'Table is unavailable'; end if; end if;
 select tax_basis_points,service_charge_basis_points into v_tax,v_service from restaurant_settings where id=1;
 insert into orders(order_type,table_id,cashier_id,customer_name,customer_phone,instructions,status) values ((p_payload->>'orderType')::order_type,nullif(p_payload->>'tableId','')::uuid,auth.uid(),nullif(p_payload->>'customerName',''),nullif(p_payload->>'customerPhone',''),nullif(p_payload->>'instructions',''),'CONFIRMED') returning id into v_order;
 insert into kot_tickets(order_id) values(v_order) returning id into v_kot;
 for v_line in select * from jsonb_array_elements(p_payload->'items') loop
   select id,name,price_paise into strict v_item from menu_items where id=(v_line->>'menuItemId')::uuid and active and available for share;
   v_line_total:=v_item.price_paise; v_variant_id:=null; v_variant_name:=null; v_variant_delta:=0;
   if nullif(v_line->>'variantId','') is not null then select id,name,price_delta_paise into strict v_variant_id,v_variant_name,v_variant_delta from menu_variants where id=(v_line->>'variantId')::uuid and menu_item_id=v_item.id and active; v_line_total:=v_line_total+v_variant_delta; end if;
   select coalesce(sum(a.price_paise),0),string_agg(a.name,', ' order by a.name) into v_addons,v_addon_names from addons a join menu_item_addons ma on ma.addon_id=a.id where ma.menu_item_id=v_item.id and a.active and a.id in (select jsonb_array_elements_text(v_line->'addonIds')::uuid);
   v_line_total:=(v_line_total+v_addons)*(v_line->>'quantity')::integer; v_subtotal:=v_subtotal+v_line_total;
   insert into order_items(order_id,menu_item_id,item_name,unit_price_paise,quantity,variant_id,variant_name,notes,line_total_paise,sent_to_kitchen) values(v_order,v_item.id,v_item.name,v_item.price_paise,(v_line->>'quantity')::integer,v_variant_id,v_variant_name,nullif(v_line->>'notes',''),v_line_total,true) returning id into v_order_item;
   insert into order_item_addons(order_item_id,addon_id,addon_name,price_paise) select v_order_item,a.id,a.name,a.price_paise from addons a join menu_item_addons ma on ma.addon_id=a.id where ma.menu_item_id=v_item.id and a.id in (select jsonb_array_elements_text(v_line->'addonIds')::uuid);
   insert into kot_items(kot_id,order_item_id,item_name,quantity,variant_name,addons_text,notes) values(v_kot,v_order_item,v_item.name,(v_line->>'quantity')::integer,v_variant_name,v_addon_names,nullif(v_line->>'notes',''));
 end loop;
 if p_payload->>'discountType'='FIXED' then v_discount=least(v_subtotal,(p_payload->>'discountValue')::bigint); elsif p_payload->>'discountType'='PERCENTAGE' then v_discount=round(v_subtotal*least((p_payload->>'discountValue')::numeric,10000)/10000); end if;
 update orders set subtotal_paise=v_subtotal,discount_paise=v_discount,tax_paise=round((v_subtotal-v_discount)*v_tax::numeric/10000),service_charge_paise=round((v_subtotal-v_discount)*v_service::numeric/10000),total_paise=(v_subtotal-v_discount)+round((v_subtotal-v_discount)*v_tax::numeric/10000)+round((v_subtotal-v_discount)*v_service::numeric/10000) where id=v_order;
 if p_payload->>'orderType'='DINE_IN' then update restaurant_tables set status='OCCUPIED' where id=(p_payload->>'tableId')::uuid; end if;
 return v_order;
end $$;

create or replace function public.append_order_items_and_create_kot(p_order_id uuid,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare v_status order_status; v_kot uuid; v_line jsonb; v_item record; v_variant_id uuid; v_variant_name text; v_variant_delta bigint; v_order_item uuid; v_addons bigint; v_names text; v_total bigint; v_tax integer; v_service integer;
begin
 if not public.has_role(array['ADMIN','CASHIER']::user_role[]) then raise exception 'Forbidden'; end if;
 select status into v_status from orders where id=p_order_id for update; if v_status in ('COMPLETED','CANCELLED') then raise exception 'Closed orders cannot be edited'; end if;
 insert into kot_tickets(order_id) values(p_order_id) returning id into v_kot;
 for v_line in select * from jsonb_array_elements(p_items) loop
  select * into strict v_item from menu_items where id=(v_line->>'menuItemId')::uuid and active and available; v_variant_id:=null; v_variant_name:=null; v_variant_delta:=0; v_total:=v_item.price_paise;
  if nullif(v_line->>'variantId','') is not null then select id,name,price_delta_paise into strict v_variant_id,v_variant_name,v_variant_delta from menu_variants where id=(v_line->>'variantId')::uuid and menu_item_id=v_item.id and active; v_total:=v_total+v_variant_delta; end if;
  select coalesce(sum(a.price_paise),0),string_agg(a.name,', ') into v_addons,v_names from addons a join menu_item_addons m on m.addon_id=a.id where m.menu_item_id=v_item.id and a.id in(select jsonb_array_elements_text(v_line->'addonIds')::uuid);
  v_total=(v_total+v_addons)*(v_line->>'quantity')::int;
  insert into order_items(order_id,menu_item_id,item_name,unit_price_paise,quantity,variant_id,variant_name,notes,line_total_paise,sent_to_kitchen) values(p_order_id,v_item.id,v_item.name,v_item.price_paise,(v_line->>'quantity')::int,v_variant_id,v_variant_name,nullif(v_line->>'notes',''),v_total,true) returning id into v_order_item;
  insert into order_item_addons(order_item_id,addon_id,addon_name,price_paise) select v_order_item,a.id,a.name,a.price_paise from addons a join menu_item_addons m on m.addon_id=a.id where m.menu_item_id=v_item.id and a.id in(select jsonb_array_elements_text(v_line->'addonIds')::uuid);
  insert into kot_items(kot_id,order_item_id,item_name,quantity,variant_name,addons_text,notes) values(v_kot,v_order_item,v_item.name,(v_line->>'quantity')::int,v_variant_name,v_names,nullif(v_line->>'notes',''));
 end loop;
 select tax_basis_points,service_charge_basis_points into v_tax,v_service from restaurant_settings where id=1;
 update orders o set subtotal_paise=x.subtotal,tax_paise=round((x.subtotal-o.discount_paise)*v_tax::numeric/10000),service_charge_paise=round((x.subtotal-o.discount_paise)*v_service::numeric/10000),total_paise=(x.subtotal-o.discount_paise)+round((x.subtotal-o.discount_paise)*v_tax::numeric/10000)+round((x.subtotal-o.discount_paise)*v_service::numeric/10000) from (select sum(line_total_paise)::bigint subtotal from order_items where order_id=p_order_id) x where o.id=p_order_id;
 return v_kot;
end $$;

create or replace function public.update_kot_status(p_kot_id uuid,p_status kot_status) returns void language plpgsql security definer set search_path=public as $$ declare v_order uuid; begin if not public.has_role(array['ADMIN','KITCHEN']::user_role[]) then raise exception 'Forbidden'; end if; update kot_tickets set status=p_status where id=p_kot_id and ((status='NEW' and p_status='PREPARING') or (status='PREPARING' and p_status='READY')) returning order_id into v_order; if not found then raise exception 'Invalid KOT transition'; end if; if p_status='PREPARING' then update orders set status='PREPARING' where id=v_order and status='CONFIRMED'; elsif not exists(select 1 from kot_tickets where order_id=v_order and status<>'READY') then update orders set status='READY' where id=v_order; end if; end $$;
create or replace function public.generate_order_bill(p_order_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare v_table uuid; begin if not public.has_role(array['ADMIN','CASHIER']::user_role[]) then raise exception 'Forbidden'; end if; update orders set status='SERVED' where id=p_order_id and status='READY' returning table_id into v_table; if not found then raise exception 'Only ready orders can be billed'; end if; if v_table is not null then update restaurant_tables set status='BILLING' where id=v_table; end if; end $$;
create or replace function public.complete_order_payment(p_order_id uuid,p_method payment_method,p_idempotency_key uuid) returns void language plpgsql security definer set search_path=public as $$ declare v_order orders%rowtype; begin if not public.has_role(array['ADMIN','CASHIER']::user_role[]) then raise exception 'Forbidden'; end if; if exists(select 1 from payments where idempotency_key=p_idempotency_key) then return; end if; select * into v_order from orders where id=p_order_id for update; if v_order.status in ('COMPLETED','CANCELLED') or v_order.payment_status='PAID' then raise exception 'Order is already closed'; end if; if v_order.status not in ('READY','SERVED') then raise exception 'Order is not ready for payment'; end if; insert into payments(order_id,amount_paise,method,idempotency_key,received_by) values(p_order_id,v_order.total_paise,p_method,p_idempotency_key,auth.uid()); update orders set payment_status='PAID',payment_method=p_method,status='COMPLETED' where id=p_order_id; if v_order.table_id is not null then update restaurant_tables set status='AVAILABLE' where id=v_order.table_id; end if; end $$;
create or replace function public.cancel_order(p_order_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare v_order orders%rowtype; begin if not public.has_role(array['ADMIN','CASHIER']::user_role[]) or length(trim(p_reason))<3 then raise exception 'A valid cancellation reason is required'; end if; select * into v_order from orders where id=p_order_id for update; if v_order.status in ('COMPLETED','CANCELLED') then raise exception 'Closed orders cannot be cancelled'; end if; update orders set status='CANCELLED',cancellation_reason=trim(p_reason),cancelled_by=auth.uid(),cancelled_at=now() where id=p_order_id; if v_order.table_id is not null then update restaurant_tables set status='AVAILABLE' where id=v_order.table_id; end if; insert into audit_logs(actor_id,action,entity_type,entity_id,old_data,new_data) values(auth.uid(),'ORDER_CANCELLED','order',p_order_id,jsonb_build_object('status',v_order.status),jsonb_build_object('status','CANCELLED','reason',trim(p_reason))); end $$;

create or replace function public.dashboard_metrics() returns table(total_sales_paise bigint,total_orders bigint,completed_orders bigint,cancelled_orders bigint,cash_paise bigint,upi_paise bigint,card_paise bigint) language sql stable security definer set search_path=public as $$ select coalesce(sum(total_paise) filter(where status='COMPLETED'),0)::bigint,count(*)::bigint,count(*) filter(where status='COMPLETED')::bigint,count(*) filter(where status='CANCELLED')::bigint,coalesce(sum(total_paise) filter(where status='COMPLETED' and payment_method='CASH'),0)::bigint,coalesce(sum(total_paise) filter(where status='COMPLETED' and payment_method='UPI'),0)::bigint,coalesce(sum(total_paise) filter(where status='COMPLETED' and payment_method='CARD'),0)::bigint from orders where created_at>=current_date and public.has_role(array['ADMIN']::user_role[]) $$;
create or replace function public.sales_last_seven_days() returns table(day text,sales_paise bigint) language sql stable security definer set search_path=public as $$ select to_char(d,'Dy'),coalesce(sum(o.total_paise),0)::bigint from generate_series(current_date-6,current_date,'1 day') d left join orders o on o.created_at>=d and o.created_at<d+'1 day'::interval and o.status='COMPLETED' where public.has_role(array['ADMIN']::user_role[]) group by d order by d $$;
create or replace function public.top_selling_items(p_limit int default 5) returns table(item_name text,quantity bigint,sales_paise bigint) language sql stable security definer set search_path=public as $$ select oi.item_name,sum(oi.quantity)::bigint,sum(oi.line_total_paise)::bigint from order_items oi join orders o on o.id=oi.order_id where o.status='COMPLETED' and public.has_role(array['ADMIN']::user_role[]) group by oi.item_name order by 2 desc limit p_limit $$;
create or replace function public.item_sales_report() returns table(item_name text,quantity bigint,sales_paise bigint) language sql stable security definer set search_path=public as $$ select oi.item_name,sum(oi.quantity)::bigint,sum(oi.line_total_paise)::bigint from order_items oi join orders o on o.id=oi.order_id where o.status='COMPLETED' and public.has_role(array['ADMIN']::user_role[]) group by oi.item_name order by 2 desc $$;
create or replace function public.payment_method_report() returns table(payment_method text,transactions bigint,total_paise bigint) language sql stable security definer set search_path=public as $$ select method::text,count(*)::bigint,sum(amount_paise)::bigint from payments where status='PAID' and public.has_role(array['ADMIN']::user_role[]) group by method $$;
create or replace function public.sales_report(p_period text default 'daily') returns table(period text,orders bigint,sales_paise bigint) language sql stable security definer set search_path=public as $$ select case when p_period='monthly' then to_char(created_at,'YYYY-MM') when p_period='weekly' then to_char(date_trunc('week',created_at),'YYYY-MM-DD') else to_char(created_at,'YYYY-MM-DD') end,count(*)::bigint,sum(total_paise)::bigint from public.orders where status='COMPLETED' and public.has_role(array['ADMIN']::user_role[]) group by 1 order by 1 desc $$;

grant execute on function public.create_order_with_kot(jsonb),public.append_order_items_and_create_kot(uuid,jsonb),public.update_kot_status(uuid,kot_status),public.generate_order_bill(uuid),public.complete_order_payment(uuid,payment_method,uuid),public.cancel_order(uuid,text),public.dashboard_metrics(),public.sales_last_seven_days(),public.top_selling_items(int),public.item_sales_report(),public.payment_method_report(),public.sales_report(text) to authenticated;
alter publication supabase_realtime add table public.kot_tickets,public.orders;
insert into public.restaurant_settings(id) values(1) on conflict do nothing;
